name: Release Package Version
on:
  push:
    branches:
      - master
    #tags:
     # - v*     
jobs: 
  build:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:    
    
    - name: Print Tag Ref
      run: echo $GITHUB_REF
      
    - name: Extract Version Number
      uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: 'refs/head/v0.9'
        regex: '[0-9.]+'
       
    - name: Print Version Number
      run: echo '${{ steps.regex-match.outputs.match }}'
      
    - uses: actions/checkout@v2
    - name: Setup .NET  
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Fruitless/Fruitless.csproj
      
    - name: Build
      run: dotnet build ./Fruitless/Fruitless.csproj
