name: Release Package Version
on:
  push:
    tags:
      - v*     
jobs: 
  build:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:    
    - name: Extract Version Number     
      id: verion-number
      uses: frabert/replace-string-action@9b62dfe3ae936b1cc380f2421c8ac9e63a4a3e85      
      with:
        pattern: '[a-z0-9A-Z\/]+v'
        string: $GITHUB_REF
    - name: Print Version Number
      run: echo ${{steps.version-number.outputs.replaced}}
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Fruitless/Fruitless.csproj
      
    - name: Build
      run: dotnet build ./Fruitless/Fruitless.csproj
