name: Release Package Version
on:
  push:
    tags:
      - v*      
jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Tag Name
      run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Fruitless/Fruitless.csproj
      
    - name: Build
      run: dotnet build ./Fruitless/Fruitless.csproj
