name: Release Package Version
on:
  push:
    #branches: [ main ]
    tags:
     - v*     
jobs: 
  build:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:    
    
    - name: Print Tag Ref
      run: echo $GITHUB_REF
      
    - name: Extract Version Number
      uses: actions-ecosystem/action-regex-match@v2
      id: regex-match
      with:
        text: ${{ github.ref }}
        regex: '[0-9.]+'
       
    - name: Print Version Number
      run: echo '${{ steps.regex-match.outputs.match }}'
      
    - uses: actions/checkout@v2
    - name: Setup .NET  
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./Fruitless/Fruitless.csproj
      
    - name: Build
      run: dotnet build ./Fruitless/Fruitless.csproj
      
    - name: Pack
      run: dotnet pack ./Fruitless/Fruitless.csproj -p:PackageVersion='${{ steps.regex-match.outputs.match }}' --output packages
      
    - name: Upload Package
      uses: actions/upload-artifact@v2
      with:
        name: fruitless-'${{ steps.regex-match.outputs.match }}'
        path: packages/
